flask_site/about/models.py
from datetime import datetime

from flask_site import db


class About(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    title_description = db.Column(db.Text())
    red_intro = db.Column(db.String())
    black_intro = db.Column(db.String())
    intro_description = db.Column(db.Text())
    first_offer = db.Column(db.String())
    first_offer_description = db.Column(db.Text())
    second_offer = db.Column(db.String())
    second_offer_description = db.Column(db.Text())
    third_offer = db.Column(db.String())
    third_offer_description = db.Column(db.Text())
    first_step = db.Column(db.String())
    first_step_description = db.Column(db.Text())
    second_step = db.Column(db.String())
    second_step_description = db.Column(db.Text())
    third_step = db.Column(db.String())
    third_step_description = db.Column(db.Text())
    edited = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    def __repr__(self):
        return self.title

flask_site/blog/models.py
from datetime import datetime

from slugify import slugify

from flask_site import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    intro = db.Column(db.String(200))
    body = db.Column(db.Text(), nullable=False)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    author_name = db.Column(db.String, db.ForeignKey('author.username'))
    author = db.relationship("Author", back_populates="posts")

    @property
    def slugified_title(self):
        return slugify(self.title)

    def __repr__(self):
        return 'Post {}'.format(self.title)

flask_site/contact/models.py
from datetime import datetime

from flask_site import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    sub_title = db.Column(db.Text())
    body = db.Column(db.Text())
    edited = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    def __repr__(self):
        return self.title


class ContactThankYou(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    intro = db.Column(db.String())
    body = db.Column(db.Text())
    edited = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    def __repr__(self):
        return self.intro

flask_site/main/models.py
from datetime import datetime

from flask_site import db


class Home(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    title_description = db.Column(db.Text())
    about_intro = db.Column(db.String())
    about_description = db.Column(db.Text())
    first_card_title = db.Column(db.String())
    first_card_description = db.Column(db.Text())
    second_card_title = db.Column(db.String())
    second_card_description = db.Column(db.Text())
    third_card_title = db.Column(db.String())
    third_card_description = db.Column(db.Text())
    blog_intro = db.Column(db.String())
    blog_title = db.Column(db.Text())
    edited = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    def __repr__(self):
        return self.title

flask_site/universal_page/models.py
from flask_site import db


class UniversalPage(db.Model):
    name = db.Column(db.String(64), nullable=False)
    url = db.Column(db.Unicode(20), unique=True, nullable=False)
    id = db.Column(db.Integer, primary_key=True)


class WhiteHeaderWithButton(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    header_text = db.Column(db.String, nullable=False)
    button_text = db.Column(db.String, nullable=False)
    button_url = db.Column(db.String, nullable=False)
    order_whiteheaderwithbutton = db.Column(db.Integer)
    whiteheaderwithbutton_id = db.Column(db.Integer, db.ForeignKey(UniversalPage.id))
    whiteheaderwithbutton = db.relationship(UniversalPage, backref='whiteheaderwithbutton')


class ThreeColumnsWithHeaders(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    column_no_1_header = db.Column(db.String, nullable=False)
    column_no_1_text = db.Column(db.Text, nullable=False)
    column_no_2_header = db.Column(db.String, nullable=False)
    column_no_2_text = db.Column(db.Text, nullable=False)
    column_no_3_header = db.Column(db.String, nullable=False)
    column_no_3_text = db.Column(db.Text, nullable=False)
    order_threecolumnswithheaders = db.Column(db.Integer)

    threecolumnswithheaders_id = db.Column(db.Integer, db.ForeignKey(UniversalPage.id))
    threecolumnswithheaders = db.relation(UniversalPage, backref='threecolumnswithheaders')


class BlockQuoteWithHeader(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    header_text = db.Column(db.Text, nullable=False)
    paragraph_text = db.Column(db.Text, nullable=False)
    order_blockquotewithheader = db.Column(db.Integer)

    blockquotewithheader_id = db.Column(db.Integer, db.ForeignKey(UniversalPage.id))
    blockquotewithheader = db.relation(UniversalPage, backref='blockquotewithheader')


class Faq(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.String, nullable=False)
    answer = db.Column(db.Text, nullable=False)
    order_faq = db.Column(db.Integer)

    faq_id = db.Column(db.Integer, db.ForeignKey(UniversalPage.id))
    faq = db.relation(UniversalPage, backref='faq')


class GreyHeader(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    header = db.Column(db.String, nullable=False)
    order_greyheader = db.Column(db.Integer, nullable=False)

    greyheader_id = db.Column(db.Integer, db.ForeignKey(UniversalPage.id))
    greyheader = db.relation(UniversalPage, backref='greyheader')


class SmallGreyHeader(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    header = db.Column(db.String, nullable=False)
    order_smallgreyheader = db.Column(db.Integer)

    smallgreyheader_id = db.Column(db.Integer, db.ForeignKey(UniversalPage.id))
    smallgreyheader = db.relation(UniversalPage, backref='smallgreyheader')


class BlockQuote(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    header = db.Column(db.String, nullable=False)
    order_blockquote = db.Column(db.Integer)

    blockquote_id = db.Column(db.Integer, db.ForeignKey(UniversalPage.id))
    blockquote = db.relation(UniversalPage, backref='blockquote')

flask_site/contact/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class ContactForm(FlaskForm):
    name = StringField('Your Name: ', validators=[DataRequired()])
    email = StringField('Your email: ', validators=[DataRequired()])
    subject = StringField('Subject: ', validators=[DataRequired()])
    body = TextAreaField('Your message: ', validators=[DataRequired()])
    submit = SubmitField('Send')

flask_site/__init__.py
import os

from flask import Flask
from flask_admin import Admin
from flask_admin.menu import MenuLink
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy

from flask_site import config
from flask_site.config import DevelopmentConfig

db = SQLAlchemy()
manager = Manager()
mail = Mail()


def create_app():
    app = Flask(__name__, instance_relative_config=True)

    config_name = os.getenv('FLASK_ENV')

    app.config.from_object(config.config[config_name])
    app.config.from_pyfile('application.cfg', silent=True)

    db.init_app(app)
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    migrate = Migrate(app, db)
    mail.init_app(app)
    manager.add_command('db', MigrateCommand)

    from flask_site.blog.models import Post
    from flask_site.users.models import Author
    from flask_site.about.models import About
    from flask_site.admin import AdminPostView, AdminUserView, AdminPageView, ContactThankYouAdminPageView, \
        UniversalPageAdmin, RolePageView, LogoutAdminMenuLink
    from flask_site.contact.models import Contact, ContactThankYou
    from flask_site.main.models import Home
    from flask_site.universal_page.models import UniversalPage
    from flask_site.users.models import Role

    admin = Admin(app, index_view=AdminPostView(Post, db.session, url='/admin'))

    admin.add_view(AdminUserView(Author, db.session))
    admin.add_view(AdminPageView(About, db.session))
    admin.add_view(AdminPageView(Home, db.session))
    admin.add_view(AdminPageView(Contact, db.session))
    admin.add_view(ContactThankYouAdminPageView(ContactThankYou, db.session))
    admin.add_view(UniversalPageAdmin(UniversalPage, db.session))
    admin.add_view(RolePageView(Role, db.session))
    admin.add_link(LogoutAdminMenuLink(name='Logout', url='/logout'))
    admin.add_link(MenuLink(name="Home Page", url='/'))

    from flask_site.main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/')

    from flask_site.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/')

    from flask_site.universal_page import universal_page as universal_page_blueprint
    app.register_blueprint(universal_page_blueprint, url_prefix='/')

    from flask_site.users import users as users_blueprint
    app.register_blueprint(users_blueprint, url_prefix='/users')

    from flask_site.blog import blog as blog_blueprint
    app.register_blueprint(blog_blueprint, url_prefix='/blog')

    from flask_site.about import about_us as about_blueprint
    app.register_blueprint(about_blueprint, url_prefix='/about')

    from flask_site.contact import contact_us as contact_blueprint
    app.register_blueprint(contact_blueprint, url_prefix='/contact')

    from flask_site.about import views, models
    from flask_site.main import views, models
    from flask_site.contact import views, models
    from flask_site.universal_page import views, models

    @login_manager.user_loader
    def load_user(author_id):
        return Author.query.get(int(author_id))

    return app

flask_site/about/__init__.py
from flask import Blueprint

about_us = Blueprint('about_us', __name__)

from . import views

about_us.add_url_rule('/', view_func=views.AboutPage.as_view('about_us'))

flask_site/about/views.py
from flask import render_template

from flask_site.about.models import About
from flask_site.common.views import PageView


class AboutPage(PageView):
    def get(self, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx.update({
            'about': About.query.filter_by(id=1).first(),
        })
        return render_template('about/about.html', **ctx)

flask_site/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views

blog.add_url_rule('/', view_func=views.BlogPage.as_view('blog_page'))
blog.add_url_rule('/<int:id>/<year>/<month>/<slug>', view_func=views.PostPage.as_view('post'))

flask_site/blog/views.py
from flask import render_template, request

from flask_site import config
from flask_site.blog.models import Post
from flask_site.common.views import PageView


class BlogPage(PageView):
    def get(self, **kwargs):
        ctx = self.get_context_data(**kwargs)
        page = request.args.get('page', 1, type=int)
        ctx.update({
            'posts': Post.query.order_by(Post.timestamp.desc()).paginate(page, config.Config.POSTS_PER_PAGE, False),
        })
        return render_template('blog/blog_page.html', **ctx)


class PostPage(PageView):
    def get(self, id, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx.update({
            'post': Post.query.get_or_404(id)
        })
        return render_template('blog/post_page.html', **ctx)

flask_site/common/views.py
from flask.views import MethodView


class ContextMixin:
    extra_context = None

    def get_context_data(self, **kwargs):
        if self.extra_context is not None:
            kwargs.update(self.extra_context)
        return kwargs


class PageView(ContextMixin, MethodView):

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        from flask_site.universal_page.models import UniversalPage
        ctx.update({
            'pages': UniversalPage.query.all(),
        })
        return ctx

flask_site/contact/__init__.py
from flask import Blueprint

contact_us = Blueprint('contact_us', __name__)

from . import views

contact_us.add_url_rule('/', view_func=views.ContactPage.as_view('contact_us'))
contact_us.add_url_rule('/thank-you', view_func=views.ContactThankYouPage.as_view('thank_you'))

flask_site/contact/views.py
from flask import render_template, request, redirect, current_app

from flask_mail import Message

from flask_site import mail
from flask_site.common.views import PageView
from flask_site.contact.forms import ContactForm
from flask_site.contact.models import Contact, ContactThankYou


class ContactThankYouPage(PageView):

    def get(self, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx.update({
            'contact': ContactThankYou.query.filter_by(id=1).first(),
        })
        return render_template('contact/contact_thank_you.html', **ctx)


class ContactPage(PageView):

    def get(self, **kwargs):
        form = ContactForm()
        ctx = self.get_context_data(**kwargs)
        ctx.update({
            'contact': Contact.query.filter_by(id=1).first(),
            'form': form
        })
        return render_template('contact/contact.html', **ctx)

    def post(self, **kwargs):
        ctx = self.get_context_data(**kwargs)

        ctx.update({
            'contact': Contact.query.filter_by(id=1).first(),
            'name': request.form['name'],
            'email': request.form['email'],
            'subject': request.form['subject'],
            'body': request.form['body']
        })
        send_email(current_app.config['MAIL_USERNAME'], **ctx)

        return redirect('thank-you')


def send_email(recipients, **ctx):
    page = render_template('contact/email.html', **ctx)
    msg = Message(ctx['subject'], sender=ctx['name'], recipients=[recipients], html=page, reply_to=ctx['email'])
    mail.send(msg)

flask_site/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

main.add_url_rule('/', view_func=views.HomePage.as_view('main'))

flask_site/main/views.py
from flask import render_template

from flask_site.blog.models import Post
from flask_site.common.views import PageView
from flask_site.main.models import Home


class HomePage(PageView):
    def get(self, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx.update({
            'home': Home.query.filter_by(id=1).first(),
            'posts': Post.query.order_by(Post.timestamp.desc())[:3],
        })
        return render_template('index.html', **ctx)

flask_site/universal_page/__init__.py
from flask import Blueprint

universal_page = Blueprint('universal_page', __name__)

from . import views

universal_page.add_url_rule('/<url>', view_func=views.SamplePage.as_view('render_page'))

flask_site/universal_page/views.py
from flask import render_template

from flask_site.common.views import PageView
from flask_site.universal_page.models import UniversalPage


class SamplePage(PageView):

    def dispatch_request(self, *args, **kwargs):

        ctx = self.get_context_data(**kwargs)
        url = ctx['url']
        page = UniversalPage.query.filter_by(url=url).first()

        block_order_list = []
        block_models = ['whiteheaderwithbutton', 'smallgreyheader', 'blockquotewithheader', 'faq', 'greyheader',
                        'threecolumnswithheaders', 'blockquote']

        if page:
            for model in block_models:
                if getattr(page, model):

                    blocks_quantity = len(getattr(page, model))
                    for number in range(blocks_quantity):

                        block_order_name = 'order_' + model
                        order = getattr(getattr(page, model)[number], block_order_name)
                        current_block = getattr(page, model)[number]
                        attributes_list = []
                        model_columns = current_block.__table__.columns._data.keys()
                        for value in model_columns:
                            attributes_list.append(value)

                        attribute_values = []
                        for element in attributes_list:
                            attribute_values.append(getattr(current_block, element))

                        block_order_list.append((str(order), model, attribute_values))
        sorted_list = sorted(block_order_list)

        return render_template('universal_page/universal_page.html', page=page, sorted_list=sorted_list, **ctx)

flask_site/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

flask_site/templates/base.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block styles %}

            <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/et-line-icons.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/themify-icons.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/swiper.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/justified-gallery.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/revolution/settings.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/revolution/layers.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/revolution/navigation.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootsnav.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">

        {% endblock %}

    </head>
    <body>

    {% block header %}
        {% include 'header.html' %}
    {% endblock %}


    {% block content %}
    {% endblock %}


    {% block footer %}
        {% include 'footer.html' %}
    {% endblock %}

    {% block scripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-migrate-3.0.1.min.js"
            integrity="sha256-F0O1TmEa4I8N24nY0bya59eP6svWcshqX1uzwaWC4F4=" crossorigin="anonymous"></script>

        <script src="{{ url_for('static', filename='js/modernizr.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
        <script src="{{ url_for('static', filename='js/skrollr.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/smooth-scroll.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.appear.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootsnav.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.nav.js') }}"></script>
        <script src="{{ url_for('static', filename='js/wow.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/page-scroll.js') }}"></script>
        <script src="{{ url_for('static', filename='js/swiper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.count-to.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.stellar.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.magnific-popup.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/isotope.pkgd.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/imagesloaded.pkgd.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/classie.js') }}"></script>
        <script src="{{ url_for('static', filename='js/hamburger-menu.js') }}"></script>
        <script src="{{ url_for('static', filename='js/counter.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.fitvids.js') }}"></script>
        <script src="{{ url_for('static', filename='js/equalize.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/skill.bars.jquery.js') }}"></script>
        <script src="{{ url_for('static', filename='js/justified-gallery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.easypiechart.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/instafeed.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/retina.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/revolution/jquery.themepunch.tools.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/revolution/jquery.themepunch.revolution.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/company_site.js') }}"></script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>

        {% endblock %}
    </body>
</html>

flask_site/templates/footer.html
<footer class="footer-standard">
    <div class="bg-light-gray padding-50px-tb text-center xs-padding-30px-tb">
        <div class="container">
            <div class="border-color-extra-light-gray border-top padding-40px-top xs-padding-30px-top">
                <div class="row">
                    <div class="col-md-12 col-xs-12 text-center">&COPY; 2019</div>
                </div>
            </div>
        </div>
    </div>
</footer>

flask_site/templates/header.html
<header>
    {% include 'navbar.html' %}
</header>

flask_site/templates/index.html
{% extends "base.html" %}

{% block title %}
    Sample company site
{% endblock %}

{% block content %}

    <section class="wow fadeIn parallax" data-stellar-background-ratio="0.5">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 extra-small-screen display-table page-title-large">
                    <div class="display-table-cell vertical-align-middle text-center">
                        <h1 class="text-extra-dark-gray alt-font font-weight-600 letter-spacing-minus-1 margin-10px-bottom">
                            {{ home.title }}
                        </h1>
                        <span class="opacity6 alt-font">{{ home.title_description }}</span>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="wow fadeIn bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-11 col-xs-12 center-col text-center wow fadeInUp margin-eight-bottom">
                    <div class="alt-font text-medium-gray margin-5px-bottom text-uppercase text-small">{{ home.about_intro }}</div>
                    <h6 class="font-weight-300 text-extra-dark-gray no-margin-bottom">{{ home.about_description }}</h6>
                </div>
            </div>
            <div class="row equalize xs-equalize-auto">
                <div class="col-md-4 col-sm-4 col-xs-12 sm-margin-four-bottom xs-margin-30px-bottom wow fadeInUp">
                    <div class="bg-white text-center">
                        <div class="padding-45px-all sm-padding-15px-all inner-match-height">
                            <span class="text-extra-dark-gray font-weight-600 display-block alt-font margin-10px-bottom">{{ home.first_card_title }}</span>
                            <p>{{ home.first_card_description }}</p>
                            <a href="{{ url_for('about_us.about_us') }}" class="btn btn-small btn-rounded btn-transparent-dark-gray">About Us <i class="ti-arrow-right"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-4 col-xs-12 sm-margin-four-bottom xs-margin-30px-bottom wow fadeInUp" data-wow-delay="0.2s">
                    <div class="bg-white text-center">
                        <div class="padding-45px-all sm-padding-15px-all inner-match-height">
                            <span class="text-extra-dark-gray font-weight-600 display-block alt-font margin-10px-bottom">{{ home.second_card_title }}</span>
                            <p>{{ home.second_card_description }}</p>
                            <a href="{{ url_for('contact_us.contact_us') }}" class="btn btn-small btn-rounded btn-transparent-dark-gray">Contact Us <i class="ti-arrow-right"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-4 col-xs-12 sm-margin-four-bottom xs-no-margin-bottom wow fadeInUp" data-wow-delay="0.4s">
                    <div class="bg-white text-center">
                        <div class="padding-45px-all sm-padding-15px-all inner-match-height">
                            <span class="text-extra-dark-gray font-weight-600 display-block alt-font margin-10px-bottom">{{ home.third_card_title }}</span>
                            <p>{{ home.third_card_description }}</p>
                            <a href="{{ url_for('blog.blog_page') }}" class="btn btn-small btn-rounded btn-transparent-dark-gray">Blog <i class="ti-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="wow fadeIn hover-option4 blog-post-style3">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-6 col-xs-12 center-col margin-eight-bottom sm-margin-40px-bottom xs-margin-30px-bottom text-center">
                    <div class="alt-font text-medium-gray margin-5px-bottom text-uppercase text-small">{{ home.blog_intro }}</div>
                    <h5 class="alt-font text-extra-dark-gray font-weight-600">{{ home.blog_title }}</h5>
                </div>
            </div>


            <div class="row equalize xs-equalize-auto">
                {% for post in posts %}
                    <div class="grid-item col-md-4 col-sm-6 col-xs-12 wow fadeInUp sm-padding-30px-bottom xs-text-center">
                        <div class="blog-post bg-light-gray inner-match-height">
                            <div class="post-details padding-40px-all sm-padding-20px-all">
                                <a href="{{ url_for('blog.post', year=post.timestamp.year, month='{:02d}'.format(post.timestamp.month),
                                    slug=post.slugified_title, id=post.id) }}" class="alt-font post-title text-medium text-extra-dark-gray width-100 display-block md-width-100 margin-15px-bottom">
                                    {{post.title}}
                                </a>
                                <p>
                                    {% if post.intro %}
                                        {{ post.intro  | truncate(100) }}
                                    {% else %}
                                        {{ post.body | striptags | truncate(100) }}
                                    {% endif %}
                                </p>
                                <div class="separator-line-horrizontal-full bg-medium-gray margin-20px-tb"></div>
                                <div class="author">
                                    <span class="text-medium-gray text-uppercase text-extra-small display-inline-block sm-display-block sm-margin-10px-top">
                                        by <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="text-medium-gray">{{post.author.username}}</a>&nbsp;&nbsp;|&nbsp;&nbsp;
                                        {{ post.timestamp.strftime('%d.%m.%Y') }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}